### ISSUE TITLE
Mute Seamail/LFG

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#136]
Similar to forums, consider adding the ability to mute seamail conversations. This is distinct from blocking a user because then they can basically never communicate.

Use Case: Someone's friend group is far too chatty and they don't want to receive notifications, but don't want to be removed from the open chat or force their friends to make a new chat.

**Comment by challfry** [comment]
This should get rolled into a general feature where we provide users the ability to control what notifications they receive.
