### ISSUE TITLE
Add registration codes

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#137]
Not necessarily useful for boat, but for the beta and other deployments it would be great to have a way to add new registration codes later on. Currently the database must be re-seeded to add more codes. Adding an additional migration to load more codes feels far too heavy handed.

Consider seeding more than 10 default codes?

**Comment by hendricksond** [comment]
If this feature is added, ensure it is disabled and as locked out as possible when on boat.

**Comment by cohoe** [comment]
Since we're gonna reset the beta anyway, the need for this has gone away. I'm just gonna seed it with more codes.
