### ISSUE TITLE
categoryForumsHandler should return actual postCount

### ISSUE THREAD

**Issue by discogestalt** [jocosocial/swiftarr#139]
You can replicate this in the development data set by logging in as any test user except `james` and then muting `james`. 

Once `james` is muted, pulling the `CategoryData` for `Egype` category returns two forum threads, with the `ForumListData` for the "Long Thread  Is Long" thread having a `postCount` of 618, but `readCount` reflects the actual number of posts, so if you're caught up in this forum the `readCount` is 825. This is immediately problematic because trusting the simple calculation with those numbers gives the user an unread post count of -207. Beyond that, this behavior contradicts how the forum post endpoints are supposed to work (see issue #138). Based on that, the `postCount` should reflect the actual number of posts, not the number minus any posts by blocked/muted users.

**Comment by challfry** [comment]
https://github.com/jocosocial/swiftarr/pull/159 fixes this; postCount and readCount both contain values that reflect the number of posts the user can currently see.
