### ISSUE TITLE
Option to delete event forum on schedule re-import

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#146]
For the Beta it would be cool if we could delete all event forums when we reload a new years schedule. Otherwise we will continue to build up many many event forums.

**Comment by challfry** [comment]
When we import a schedule we store the UID of each event. When we import an updated schedule the differencing algorithm should match UIDs for updated events and update the existing Event in the db (and keep that event's associated Forum thread). 

This assumes that the updated schedule is actually an update of the existing schedule and not the San Diego Comic-Con schedule (or the 2020 JoCo schedule). But generally we shouldn't be seeing an exploding of event forums.

**Comment by cohoe** [comment]
I suspect the spread of UIDs between 2022 and 2023 schedules to be quite high.

**Comment by cohoe** [comment]
Given the management command I don't think this option needs to be developed further.
