### ISSUE TITLE
Make open chat the default state

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#179]
Defaulting to yes increases options. Consider making all seamails "open" and removing the option to opt in/out entirely.

**Comment by hendricksond** [comment]
I've been thinking about this for a few days. Defaulting to "open", great idea, we should do that. I'd also like to see an additional setting, "allow any participant to add new members", which can be toggled on and off by the chat owner.

But I think there is value in keeping the option to create a seamail thread which is permanently "closed".
