### ISSUE TITLE
Posts in chat/forum threads: Add ability to sort by ascending time (oldest to newest) alongside default (newest to oldest)

### ISSUE THREAD

**Issue by amytant** [jocosocial/swiftarr#192]
Someone suggested this to me on Boat, and it feels like a potentially good idea (in certain scenarios/use cases) to make it possible to make it so messages can be shown either in most recent to oldest order (as is the current standard) or the reverse oldest to most recent.

Sometimes you want to see old messages without having to scroll all the way down constantly.

**Comment by cohoe** [comment]
Seamail conversations cannot be sorted, so that's new functionality. Forums can be sorted in the web UI so not sure what you're referring to here?

**Comment by amytant** [comment]
@cohoe I specifically mean when you navigate away from a forum page, the selected sort method is not remember.

![Twitarr_Forums_Sorting_NotRemembered](https://user-images.githubusercontent.com/44933060/225166898-f1dddca7-9b03-48fe-b018-7d3493326df9.gif)

**Comment by amytant** [comment]
I am specifically referring to the posts/messages, not the threads/conversations themselves. It could sometimes be handy to be able to display the messages/posts from oldest to newest, instead of the default newest to oldest.

**Comment by cohoe** [comment]
Gotcha. I am unconvinced this is worth the effort at this time.

**Comment by amytant** [comment]
Certainly not high priority whatsoever. Just could be a nice feature to have.

**Comment by challfry** [comment]
One possible issue with doing this is that it would mess with how default positioning works. When you view a forum thread we store the post ID of the highest-numbered post that you viewed. When returning to the thread we start you on the page that has that post. While you can jump to the last page (and we then consider all posts viewed), we don't currently store "This user was reading this thread in reverse order, they've read the most recent X posts from the end, and we should return them to this page when they return to the thread".

**Comment by cohoe** [comment]
Given that:
1) Our UI sorting mechanisms are already somewhat dubious (don't persist very well, etc).
2) Sorting in the API would be a challenge given Chall's point above

I'm gonna close this until a more compelling case arises.
