### ISSUE TITLE
Events migration warning / no events imported

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#197]
```
[ INFO ] [Migrator] Starting prepare [database-id: psql, migration: App.ImportEvents]
event uid  dates could not be parsed
event uid  dates could not be parsed
...
...
```

This should be silent if we don't care or loud if we do.

**Comment by cohoe** [comment]
This seems to be blocking new deployments from loading the schedule. Which begs the question.... why is this happening? The schedule file seems fine.

**Comment by cohoe** [comment]
Pencil this in the "how did this ever work" bucket. The `continue` statements in https://github.com/jocosocial/swiftarr/blob/57d8e797472767be8e92a1e8a6d335b7e5eb2593/Sources/App/Helpers/EventParser.swift#L34-L45 are causing the loop to iterate prematurely and nearly no events to be imported. A single one seems to make its way in at some point. Removing the two `continue`'s leads to all events getting imported.

There are 411 "BEGIN:VEVENT" lines in the test-schedule.ics. After making the change, there are 411 in the table (`SELECT COUNT(*) FROM event;` so this seems to work. But like..... how did we get here?!?!

**Comment by cohoe** [comment]
From Chall: 

That code happens to work with the .ics files downloaded from Sched because those files are CR/LF, and the line splitter produces a blank line in between every content-containing line in the lines array. That blank line hits the 'default' case in the switch, doesn't continue, and delivers the event contents to makeEvent. The schedule.ics file is LF, and makes the parser fail. I may have converted it before checking it in (because I opened it in BBEdit).

There is a lot more than that that's wrong with that parser code, however. That code just barely works for the .ics files that Sched creates and is missing a bunch of stuff that would likely be in calendar files made by another app.

For example, the spec allows for `floating-time` dates that designate a time of day in whatever timezone you happen to be in. Sched does not appear to use these even though it would fix their timezone issue and THO could deploy a schedule that wouldn't have a deliberately wrong UTC time for events. We don't try to parse such dates since Sched doesn't create them.

**Comment by challfry** [comment]
Also, .ics files can have Timezone objects that describe relevant timezones, and then time values in Events can refer to those embedded Timezones. Sched doesn't appear to use these.

**Comment by cohoe** [comment]
Chall did major improvements to the event parser and I haven't encountered this issue since.
