### ISSUE TITLE
Incorrect forum counts after seeding

### ISSUE THREAD

**Issue by hendricksond** [jocosocial/swiftarr#199]
On boat, forums created by the seed processes (in particular, schedule loading) did not correctly update the counts of forums in a category.

**Comment by cohoe** [comment]
Events get soft-deleted in the schedule update process.
https://github.com/jocosocial/swiftarr/blob/497f1e105e439cd3400d13eebfe144a6b962628c/Sources/swiftarr/Helpers/EventParser.swift#L354

https://github.com/jocosocial/swiftarr/blob/497f1e105e439cd3400d13eebfe144a6b962628c/Sources/swiftarr/Models/Event.swift#L45-L46

However that soft-delete cascades to queries in which it gets joined, such as the query for forums within a category:
https://github.com/jocosocial/swiftarr/blob/497f1e105e439cd3400d13eebfe144a6b962628c/Sources/swiftarr/Controllers/ForumController.swift#L187

Which yields SQL of:
```
...
LEFT JOIN ""event"" ON ""forum"".""id"" = ""event"".""forum_id"" 
WHERE ... AND (""event"".""deleted_at"" IS NULL OR ""event"".""deleted_at"" > '2024-01-10 21:32:11 +0000') 
```

Thus stripping out the result from the set.

Given we put in effort to post in the [now deleted] event's forum that the event was deleted, I feel like this forum should continue to show up in the list.
