### ISSUE TITLE
Allow Moderators to Select Twarts to move them into a new Forum

### ISSUE THREAD

**Issue by daybreaker** [jocosocial/swiftarr#200]
It would be useful if Moderators could select multiple Twarts, then choose "Create Forum" as an action, so that we can remove multiple Twarts from the feed at one time, while simultaneously moving them into a new (or existing?) Forum.

(Side note: selection multiple twarts could have additional actions. Like "Delete All")

#### UX flow 

This would probably require a mod-only "select Twart" button on each Twart, and then when 1 or more are selected, display a bottom anchored action bar with "Move to Forum | Delete All | etc"

Selecting Move to Forum would create a popup with a list of the main Forum categories (General / Activities / etc), and a "new Forum Title" text box.

If we also want the ability to move tweets to an existing Forum, a second drop down would be populated after the first Forum Category dropdown is selected with a list of the existing Forum titles in that Category.

#### API side

We'd probably want to send a simple POST request, to something like: (I dont know the actual URL endpoints or model names)

`twarts/move, { forum_category_id: XX, title: 'New Title', twart_ids: [X, Y, Z] }`  

`twarts/move, { forum_category_id: XX, forum_id: YY, twart_ids: [X, Y, Z] }`  

`twarts/delete, { twart_ids: [X, Y, Z] }`

**Comment by cohoe** [comment]
What benefits do moving them to a forum post achieve? Twarrts that get moderated are still visible to mods via the mod log / report.

**Comment by daybreaker** [comment]
Sometimes we dont want to remove a twarrt, but move it into a more relevant forum. For example, last cruise, whenever anyone mentioned masking, we had to remove the twarrt then ask the user to repost as a forum in the Covid category. It would be easier if we could move a twarrt (and all replies, and/or all selected twarrts) to a forum instead of having that middle step of asking them to repost.

**Comment by cohoe** [comment]
The Twarrt stream feature has been removed at the request of THO and is unlikely to ever return.
