### ISSUE TITLE
Should admins/moderators still be allowed to see the feed even after it's turned off?

### ISSUE THREAD

**Issue by daybreaker** [jocosocial/swiftarr#201]
After THO made the decision to shut down the feed, moderators couldnt see Twarts either.

Would it be useful to allow them to, or at least maybe provide different levels of "Turned Off" for the feed, in case it just needs to be temporarily shut down while moderators go in and clean out any offending twarts?

**Comment by cohoe** [comment]
Rolled into https://github.com/jocosocial/swiftarr/issues/177
