### ISSUE TITLE
Postgres Image Broken

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#229]
Canonical has done something and the 14-22.04_beta ubuntu/postgres image doesnt work when the `user: postgres` is specified. Container exits 1. No logs, no nothing. No help in their bug tracker either. Now that Bitnami has arm64 images I'd really like to move back to using those since that's what the beta and prod deployments use.

**Comment by hendricksond** [comment]
Agree on switching to bitnami now that those images are up. Hopefully it's an easy switch!
