### ISSUE TITLE
Bad image path returns 500

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#257]
If you GET an image such as `/api/v3/image/full/abc1234.jpg` that does not exist, we return a 500 instead of something like a 404 or 403. We should improve this response.

**Comment by challfry** [comment]
If you attempt to get an image via `/api/v3/image/full/**` where the filename isn't a UUID, you'll get a 400 error. Requests with valid UUIDs that don't point to actual files now return a 404 error instead of 500-level error.
