### ISSUE TITLE
Logout on one device logs out on all devices

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#30]
If a user logs in on multiple devices (or browser contexts such as normal+incognito) if one hits logout they all get logged out.

**Comment by challfry** [comment]
This was by design, so that a user can force logout others. 

The design, however, may be bad.

Luckily there is both a session thing that tracks the individual client, and a token that attaches to all concurrent logins for that user.

**Comment by cohoe** [comment]
I think there is value in logging out all under certain circumstances as you described. I'd call the current behavior of logging out all devices surprising since no other major social service behaves this way.

**Comment by challfry** [comment]
Logout now optionally deletes the login token but always deletes the session. We also track sessions per user and show users (roughly) what devices they're logged in from on the logout screen.

I use a hilariously bad User-Agent parser to gather info on what device users are logged in from:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/8335266/163384018-672a9d94-6a77-494d-9a05-1fb368da662a.png">
