### ISSUE TITLE
Forum Search by Category/Thread

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#300]
Enhance forum searching to limit results either to a category (threads or posts) or to a thread (for post). The client apps can then implement this as well.

**Comment by challfry** [comment]
Fixed by https://github.com/jocosocial/swiftarr/commit/de60bdae3d1244df92a35689f37711553cf94967. `api/v3/forum/search/` has a new query param `?category=UUID` that enables this. Forum post search (`api/v3/forum/post/search`) already has query options to filter by forum or category.
