### ISSUE TITLE
User Import Hits Payload Too Large Error

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#329]
When testing the User Export and Import process I got a `Error: Payload Too Large` when uploading the archive of registered users. I suspect this is because the route does not have a `maxSize` specified and falls back to the default, which is 10mb.

https://github.com/jocosocial/swiftarr/blob/956e1d2c62a167cc3a6c2e155c228aef01e48646/Sources/swiftarr/Controllers/AdminController.swift#L60
https://github.com/jocosocial/swiftarr/blob/956e1d2c62a167cc3a6c2e155c228aef01e48646/Sources/swiftarr/configure.swift#L385

In other routes with large content (such as images) we specify a `.collect(maxSize: "30mb")` or similar such as with:
https://github.com/jocosocial/swiftarr/blob/956e1d2c62a167cc3a6c2e155c228aef01e48646/Sources/swiftarr/Controllers/ForumController.swift#L60

This route likely needs a significantly larger payload size (and may need HTTP app proxy config change as well). The final 2024 production bundle is 497MB.

Related - we have a setting for maxImageSize but it only applies to image processing after uploading and not to the HTTP upload.
https://github.com/jocosocial/swiftarr/blob/956e1d2c62a167cc3a6c2e155c228aef01e48646/Sources/swiftarr/Helpers/Settings.swift#L101

Further reading: https://docs.vapor.codes/basics/routing/

**Comment by challfry** [comment]
If we set the payload limit to 1gb, will the server be okay with the `.collect` body processing method? I suppose I could go look up the container settings, but asking is easier. If not, we can switch the method to use `.stream`.  

I'm pretty sure the ZIP compression module we're using streams the archive file, and once it's decompressed all the files in the archive are small. So, switching the route to stream the HTTP body should be enough to ensure the archive never needs to be held in memory--if we have to go that route.

The maxImageSize setting is for individual images, not HTTP payloads. Forum posts, for example, take up to 4 images in the HTTP body of the POST. The route handler for creating forum posts has a 30mb limit on body size; the limit on individual images is less than that, and the individual image size limit is more about keeping the server from serving out bandwidth-hogging images.

**Comment by cohoe** [comment]
I may have to make an adjustment to the Traefik proxy akin to: `"traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=200000000"`. Though after reading https://doc.traefik.io/traefik/middlewares/http/buffering/#maxrequestbodybytes and seeing the default is 0, I'm curious why I needed to do this for one of my unrelated services in the past. Regardless it's a known thing. I confirmed that it is definitely Swiftarr returning the 413 not Traefik.

That `.defaultMaxBodySize` setting makes more sense now.

**Comment by hendricksond** [comment]
Vapor's docs do recommend using `stream` for file uploads to avoid straining system memory: https://docs.vapor.codes/basics/routing/

I agree with that change - significantly increasing the file size on `collect` would make us more vulnerable to DoS attacks where people try to max out the server's memory.
