### ISSUE TITLE
Registration codes can be infinitely used

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#337]
In verifying #329 (fixed in #334) in the prod instance I found two users who appeared in the users table and not in the data dump. Chasing this down led me to discover that a users registration code can be used multiple times. The last-created user claims the "user" field in "registrationcode". I feel that this is undesirable because it can lead to the same user creating many accounts that are difficult to audit.

We have code to prevent this but there seems to be a bug: https://github.com/jocosocial/swiftarr/blob/15faff30d5803e61987bc5e3282f093a7f65f584/Sources/swiftarr/Controllers/UserController.swift#L187-L189

**Comment by challfry** [comment]
PR #341 fixes this. We now check for `RegistrationCode.$user.id` value to be nil, instead of checking `RegistrationCode.user`.
