### ISSUE TITLE
` swift run swiftarr migrate --yes` Crashing on startup

### ISSUE THREAD

**Issue by Torgen** [jocosocial/swiftarr#340]
```
💣 Program crashed: Illegal instruction at 0x00007fb503337fcc

Thread 19 crashed:

0 Settings.init() + 3089 in swiftarr at /mnt/c/Users/Dan/Documents/GitHub/swiftarr/Sources/swiftarr/Helpers/Settings.swift:172:3



1 one-time initialization function for shared + 23 in swiftarr at /mnt/c/Users/Dan/Documents/GitHub/swiftarr/Sources/swiftarr/Helpers/Settings.swift:57:22



2 0x00007fb502d66eb1 swift::threading_impl::once_slow(swift::threading_impl::once_t&, void (*)(void*), void*) + 160 in libswiftCore.so
3 Settings.shared.unsafeMutableAddressor + 22 in swiftarr at /mnt/c/Users/Dan/Documents/GitHub/swiftarr/Sources/swiftarr/Helpers/Settings.swift:57:13



4 SwiftarrConfigurator.configureBundle(_:) + 5695 in swiftarr at /mnt/c/Users/Dan/Documents/GitHub/swiftarr/Sources/swiftarr/configure.swift:146:12

   144│                 }
   145│                 configLog.notice("Seting static files path to \(resourcesURL).")
   146│                 Settings.shared.staticFilesRootPath = resourcesURL
      │            ▲
   147│                 configLog.notice("Set static files path to \(Settings.shared.staticFilesRootPath.path).")
   148│

5 SwiftarrConfigurator.configure() + 826 in swiftarr at /mnt/c/Users/Dan/Documents/GitHub/swiftarr/Sources/swiftarr/configure.swift:63:7

    61│
    62│                 // Set up all the settings that we don't need Redis to acquire.
    63│                 try configureBundle(app)
      │       ▲
    64│                 try configureBasicSettings(app)
    65│

6 static Entrypoint.main() in swiftarr at /mnt/c/Users/Dan/Documents/GitHub/swiftarr/Sources/swiftarr/entrypoint.swift:21
```

Settings.swift:172 is the declaration of `@StoredSettingsValue("allowAnimatedImages", defaultValue: true) var allowAnimatedImages: Bool`, which is the last @StoredSettingsValue.

Before the Swift 6 migration and the fix for #330, it got as far as migrations. Docker thinks redis and postgres are running. Using Debian 12 on WSL.

**Comment by challfry** [comment]
Okay. I've done several db resets and fresh migrations, and I'm not seeing this. Could you try changing that setting to a non-stored one? Settings.swift line 172 would become:
```
	@SettingsValue var allowAnimatedImages: Bool = true
```
I'm looking to see if that causes it to crash on another stored setting initializer instead.

Also. Settings eventually does a read from Redis to load in all the saved values, but it can't do it at init time as Redis isn't ready yet. So, the property wrapper just saves the name of the Redis key backing the property and sets the default value.

**Comment by cohoe** [comment]
I've had dubious results with Swift 6 on Linux (related to #323). I've been able to stabilize some things by passing `--use-integrated-swift-driver` to `swift build` and `swift run`

**Comment by Torgen** [comment]
Setting `--use-integrated-swift-driver` without code change: Crashes in the same place.

Changing the line where it crashed to @SettingsValue without the flag change: Now crashes at line 155, which is the previous @StoredSettingsValue.

**Comment by Torgen** [comment]
Tried a few more things:

* Making `StoredSettingsValue` not extend `SettingsValue`: made no difference.
* Making `StoredSettingsValue` take its default value as the wrapped value instead of as a parameter to the wrapper: crashed at `static let shared = Settings()` instead
* put a log statement at the start of the `StoredSettingsValue` initializer: It got called for all the settings in file order (!), but still claimed to have crashed at the line of the last `StoredSettingsValue`.

**Comment by Torgen** [comment]
Put logs in `SettingsValue.init` as well. Last thing it logged was 200, meaning the problem was the first URL. Wondered if it was that `URL.init(fileURLWithPath:)` is deprecated, but changing it to use `URL.init(filePath:DirectoryHint:relativeTo:)` didn't fix it. Tried changing it to an absolute path and it crashes before the next URL. So for some reason, it's the ~ in the file url that's crashing it.

**Comment by Torgen** [comment]
Changed the URL settings to
```swift
@SettingsValue var staticFilesRootPath: URL = FileManager.default.homeDirectoryForCurrentUser
@SettingsValue var userImagesRootPath: URL = URL(filePath: "./swiftarrImages", directoryHint: .isDirectory, relativeTo: FileManager.default.homeDirectoryForCurrentUser).absoluteURL
```
and it got as far as the migrations before crashing at
```
swiftarr/TimeZoneChanges.swift:70: Fatal error: Error thrown while importing time zone change data. error: Found 0 entries in the timezonechanges.txt file. We must have at least an initial timezone.
```
but at least that tells me what to do.
