### ISSUE TITLE
Privileged users need to see registration code

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#38]
An issue came up in 2022 that required looking up a users registration code. Currently this takes postgres queries to achieve. Consider adding a field to the user profile information that renders the registration code for privileged users such as Mods/THO/TwitarrTeam.

**Comment by challfry** [comment]
The Regcodes page in the Admin panel now has a 'search by user' form where you can input a partial username, get username matches, and from those view all the alt accounts and regcode for a user. Using this requires TwitarrTeam access or higher.
