### ISSUE TITLE
Private forum category and role for Shutternauts

### ISSUE THREAD

**Issue by jamesez** [jocosocial/swiftarr#40]
During the 2022 sailing, coordination of the ShutterNauts was accomplished by manually making a new daily seamail, manually re-entering every person one at a time. A missed person meant re-doing that manual process.

I'm proposing implementing a "private category" feature, where a category can be configured to a members-only privacy, and will only show to those members.

My intention is this is for staff & volunteer coordination (e.g., craft room, shutternauts, game library, etc), and not as a general-purpose feature.

I'm willing to implement this; I'm opening this issue to discuss the merits.

**Comment by cohoe** [comment]
Why did you need to create a new seamail every day? The twitarr team did a similar thing but had a persistent seamail conversation that lasted all week long.

**Comment by jamesez** [comment]
There was a daily shot list posted every night. It have been one long thread, but with 20+ people on it and a lot of additional traffic besides the shot list, and without the ability to add people (as the entire list of coordinators isn't known a priori and people get added during the sailing), it was a bit of a challenge.

I suppose we could have used a collection of seamails (one for shot lists, one for chat, one for coordinating) that could have worked, but that sounds like ... a forum. And it would have been mixed in with the other seamails.

**Comment by jamesez** [comment]
There could be a Craft Room Helpers forum with various thread like "THO requests," "issues with equipment," "who is helping when," and so on.

**Comment by cohoe** [comment]
We already have a forum category for Help Desk which I think would cover the helpers/equipment stuff. THO does not keep a super close eye on Twitarr all the time to requests to them generally go through guest services and/or their info desk (and occasionally the Help Desk category).

Given that you have a pretty large behind-the-scenes group I think it's reasonable to create a Shutternaut role similar to what we do for Moderators and TwitarrTeam. We can then present a forum category only to you and anyone with that role can post there. Would also give you the ability to upload a vew images (subject to the standard twitarr constraints).

**Comment by jamesez** [comment]
For the Shutters: that should work fine.

**Comment by challfry** [comment]
There is now a private category for Shutternauts. I've added a User Role concept to Users; the Shutternaut Manager role can add/remove the Shutternaut role for other users and the Shutternaut role lets you see the new category.

Roles work a bit differently than UserLevels as each Role gives users specific capabilities and a user can have multiple Roles, while UserLevel is just an integer and each UserLevel is always a superset of the capabilities of the level below it.
