### ISSUE TITLE
Investigate Horizontal Scaling

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#51]
Could we run multiple instances of the app? Could help cover certain crashes.

**Comment by challfry** [comment]
There's a couple of things that would need to be reworked.

First, UserCache. This is an app-wide dictionary sits in memory and maps userIDs to a bunch of basic information about each user. It requires updating when relevant user data changes, so there's updater fn calls on all the routes that mutate user data. It's faster than SQL lookups for a bunch of often-accessed data (such as building UserHeaders), but more importantly it's synchronous. Before async/await, adding code to pull a bunch of user data to fill out a response made for even deeper chained EventLoopFutures than we had. Now with async/await, an async API is less onerous. Horizontal scaling of cache would still require we add Redis pub/sub or similar to notify all copies.

However, if we make the API to UserCache async, we can try making a UserCache variant that doesn't actually cache and calls the db every time. 

Second issue is WebSockets, which are tied to the instance that creates them. We could set up a single instance to handle all the sockets or spread them out between all instances; either way we need a Redis pub/sub thing again to forward notifications from the instance where the notification happened to the instance where the socket is.

**Comment by cohoe** [comment]
Unless something dramatic happens I don't think we'll be doing this any time soon.
