### ISSUE TITLE
Improve Tweet Thread UI

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#59]
It is very difficult to follow tweet threads in the web UI. I had no idea tweet threads were even a thing until someone commented about it. Not sure how best to achieve this.

**Comment by challfry** [comment]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/8335266/163732685-c4479025-6d3e-411a-ac35-6122bf849b61.png">

The "needle with thread" emoji isn't ideal for indicating a reply thwart, but it's better than nothing until we can get some custom artwork.
