### ISSUE TITLE
Improve search visibility

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#60]
Search is buried in the trunk and changes context depending on which module/feature you're in (tweets, forums, seamail, schedule). Several users did not know they could search here. Specific example, searching by hashtag. Totally supported via the UI just somewhat hidden. We should consider adding a search hint or box somewhere on the page to make it more apparent that search is a thing.

Also explicitly call out search in the how-to guide.

**Comment by challfry** [comment]
Search is in the header bar now; it's a magnifying glass icon on the right. I haven't added anything to specifically call out hashtag and mention searches, although these are really just text searches--same as Twitter.
