### ISSUE TITLE
Data Export

### ISSUE THREAD

**Issue by cohoe** [jocosocial/swiftarr#63]
Similar to Google Takeout or other "download my data" features of big providers. A question was posed if a user could download their data. If we were to look into something like this it would have to be ONLY that users data. For privacy reasons we should not allow a user to download anything that wasn't created by them. So all Seamails become one-way, forum posts lose all context. Not sure if that's really beneficial anymore. Will leave this here in case anyone has opinions but I think the answer is going to be no.

**Comment by challfry** [comment]
Yeah, I can't make a case for how this could work in a way that'd be useful to anyone.

**Comment by cohoe** [comment]
This came up again in a couple conversations. An example was cited of writing some story type content in forum posts that are now gone to them. Contact lists (favorites) as well.

At the initial time of writing we didn't have the concept of favorite users. As we've added more to that I think there could be additional value in "auto" saving favorite user public profile data.

Another case was shutternauts wanting to know what they had photographed. Related to #510 but of a more personalized nature.
